name: siyou_b2b
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+7

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1
  provider: ^3.1.0+1
  shared_preferences: ^0.5.3+4
  intl: ^0.16.0
  dio: ^3.0.3
  easy_localization: ^1.3.1
  carousel_slider: ^2.2.1
  expandable: ^3.0.0+1
  cached_network_image: ^2.2.0+1
  flutter_rating_bar: ^3.0.0
  flutter_svg: ^0.18.1
  flare_flutter: ^1.5.9
  bottom_navy_bar: ^5.2.0
  popup_menu: ^1.0.3
  badges: ^1.1.1
  floating_bottom_navigation_bar: ^1.3.0
  shape_of_view: ^1.0.1
  dynamic_theme: ^1.0.1
  barcode_flutter: ^1.1.0
  google_maps_flutter: ^0.4.0
  flutter_icons: ^1.1.0
  geolocator: ^5.3.1
  auto_size_text: ^2.1.0   
  flutter_launch: "0.2.0"  
  url_launcher: ^5.5.0  
  floating_action_bubble: ^1.0.9
  fluttericon: ^1.0.7
  flutter_staggered_grid_view: ^0.3.0
  fluid_bottom_nav_bar: ^1.0.1
  barcode_scan_fix: ^1.0.2
  shimmer: ^1.1.1
  rflutter_alert: ^1.0.3
  #flutter_holo_date_picker: ^0.1.4
  gzx_dropdown_menu: ^2.1.0
  flutter_rounded_date_picker: ^1.0.4
  
  


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.4"
flutter_icons:
  image_path: "assets/png/logo.png"
  android: true
  ios: true
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/langs/
    - assets/svg/
    - assets/png/
    - assets/jpg/
    - assets/
    
  #    - assets/png/
  #    - assets/jpg/
  #    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
  - family:  MyFlutterApp
    fonts:
      - asset: assets/fonts/MyFlutterApp.ttf

     

        
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
